# Use official Node.js image
FROM node:16

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all other source code
COPY . .

# Expose port 3000
EXPOSE 3000

# Command to start Next.js app
CMD ["npm", "run", "dev"]