import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
    title: "Ari Next App",
    description: "Generated by Ari",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>{children}</body>
        </html>
    );
}
